export const GET_COMMENT = 'GET_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const FETCH_COMMENT_GET = 'FETCH_COMMENT_GET';
export const FETCH_COMMENT_ADD = 'FETCH_COMMENT_ADD';
export const FETCH_COMMENT_UPDATE = 'FETCH_COMMENT_UPDATE';
export const FETCH_COMMENT_REMOVE = 'FETCH_COMMENT_REMOVE';

export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START';
export const FETCH_COMMENTS_END = 'FETCH_COMMENTS_END';