export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_PENDING = 'AUTH_USER_PENDING';
export const AUTH_USER_FULFILLED = 'AUTH_USER_FULFILLED';
export const AUTH_USER_REJECTED = 'AUTH_USER_REJECTED';

export const IS_AUTH_USER = 'IS_AUTH_USER';
export const IS_AUTH_USER_PENDING = 'IS_AUTH_USER_PENDING';
export const IS_AUTH_USER_FULFILLED = 'IS_AUTH_USER_FULFILLED';
export const IS_AUTH_USER_REJECTED = 'IS_AUTH_USER_REJECTED';

export const GET_USER = 'GET_USER';
export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED';
export const GET_USER_REJECTED = 'GET_USER_REJECTED';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_PENDING = 'ADD_USER_PENDING';
export const ADD_USER_FULFILLED = 'ADD_USER_FULFILLED';
export const ADD_USER_REJECTED = 'ADD_USER_REJECTED';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED';
export const UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_FULFILLED = 'DELETE_USER_FULFILLED';
export const DELETE_USER_REJECTED = 'DELETE_USER_REJECTED';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_PENDING = 'LOGOUT_USER_PENDING';
export const LOGOUT_USER_FULFILLED = 'LOGOUT_USER_FULFILLED';
export const LOGOUT_USER_REJECTED = 'LOGOUT_USER_REJECTED';